leftnav:
- identifier: de8ecb25-830c-61ad-8279-b4d4dc508005
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: 82effbc6-0d78-a950-02bb-b94bd88aa16a
  name: Video Lectures
  url: /pages/video-lectures/
  weight: 20
- identifier: 00f1d787-7dd6-c6ab-86fa-05e23037ce9e
  name: Chapter 0. Introduction
  parent: 82effbc6-0d78-a950-02bb-b94bd88aa16a
  url: /pages/video-lectures/chapter-0--introduction
  weight: 30
- identifier: 541ed54b-ca01-1ae6-c93f-3e4894265c66
  name: Chapter 1. Fermions, Bosons, and Fields
  parent: 82effbc6-0d78-a950-02bb-b94bd88aa16a
  url: /pages/video-lectures/chapter-1--fermions-bosons-and-fields
  weight: 40
- identifier: d2b271d8-0b70-02c8-8970-68f0acab2a6d
  name: Chapter 2. Symmetries
  parent: 82effbc6-0d78-a950-02bb-b94bd88aa16a
  url: /pages/video-lectures/chapter-2--symmetries
  weight: 50
- identifier: 07284824-3e45-3cd9-63bd-762605c5e6b8
  name: Chapter 3. Feynman Calculus
  parent: 82effbc6-0d78-a950-02bb-b94bd88aa16a
  url: /pages/video-lectures/chapter-3--feynman-calculus
  weight: 60
- identifier: 261d62f3-5d97-9dd7-607b-034c59d248ec
  name: Chapter 4. QED
  parent: 82effbc6-0d78-a950-02bb-b94bd88aa16a
  url: /pages/video-lectures/chapter-4--qed
  weight: 70
- identifier: 0e3bc8fd-79ce-aa37-b689-321c9a45efd5
  name: Chapter 5. QCD
  parent: 82effbc6-0d78-a950-02bb-b94bd88aa16a
  url: /pages/video-lectures/chapter-5--qcd
  weight: 80
- identifier: eb0d6835-336c-2643-ff7d-c38be60de661
  name: Chapter 6. Weak Interactions
  parent: 82effbc6-0d78-a950-02bb-b94bd88aa16a
  url: /pages/video-lectures/chapter-6--weak-interactions
  weight: 90
- identifier: 39878e29-51df-3794-21d1-8b0550df0b1e
  name: Chapter 7. Higgs Physics
  parent: 82effbc6-0d78-a950-02bb-b94bd88aa16a
  url: /pages/video-lectures/chapter-7--higgs-physics
  weight: 100
- identifier: 220b4d88-bdd4-794e-c2b7-924fb69cb924
  name: Chapter 8. Neutrino Physics
  parent: 82effbc6-0d78-a950-02bb-b94bd88aa16a
  url: /pages/video-lectures/chapter-8--neutrino-physics
  weight: 110
- identifier: 0dd779a3-c018-49c1-7508-cac9276a60cb
  name: Chapter 9. Nuclear Physics
  parent: 82effbc6-0d78-a950-02bb-b94bd88aa16a
  url: /pages/video-lectures/chapter-9--nuclear-physics
  weight: 120
- identifier: 326619bb-bbc2-9833-89c8-83cf4898ee7a
  name: Chapter 10. Instrumentation
  parent: 82effbc6-0d78-a950-02bb-b94bd88aa16a
  url: /pages/video-lectures/chapter-10--instrumentation
  weight: 130
- identifier: 75ab9f65-e7ec-e552-10bf-b2eca4629bf0
  name: Lecture Slides
  url: /pages/lecture-slides
  weight: 140
- identifier: fb9fd190-f9d1-4fae-43ba-c049c46d74ad
  name: Recitations
  url: /pages/recitations
  weight: 150
- identifier: da408d4d-5d5b-7887-9cb1-c80727794ea6
  name: Assignments
  url: /pages/assignments
  weight: 160
title: Left Nav
